FROM i386/ubuntu:20.04 AS executor32-buildtools

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y gcc g++ cmake \
        libboost-all-dev bison qt5-default libsdl1.2-dev libsdl2-dev \
        ninja-build ruby

WORKDIR /files

