namespace Executor {
    namespace ReferenceTraps {
        void rsys_adb();
        void rsys_gestalt();
        void rsys_osutil();
        void rsys_serial();
        void rsys_stdfile();
        void base_emustubs();
        void ctl_ctl();
        void dial_dial();
        void ADB();
        void AliasMgr();
        void AppleEvents();
        void BinaryDecimal();
        void CodeFragments();
        void ControlMgr();
        void CQuickDraw();
        void DeskMgr();
        void DeviceMgr();
        void DialogMgr();
        void DiskInit();
        void Displays();
        void EditionMgr();
        void FileMgr();
        void Finder();
        void FontMgr();
        void Gestalt();
        void HelpMgr();
        void Iconutil();
        void IntlUtil();
        void ListMgr();
        void MemoryMgr();
        void MenuMgr();
        void MixedMode();
        void NotifyMgr();
        void OSEvent();
        void OSUtil();
        void Package();
        void PrintMgr();
        void ProcessMgr();
        void QuickDraw();
        void QuickTime();
        void ResourceMgr();
        void SANE();
        void ScrapMgr();
        void ScriptMgr();
        void SegmentLdr();
        void Serial();
        void ShutDown();
        void SoundMgr();
        void SpeechManager();
        void StdFilePkg();
        void SysErr();
        void TextEdit();
        void TimeMgr();
        void ToolboxEvent();
        void ToolboxUtil();
        void VRetraceMgr();
        void WindowMgr();
        void list_list();
        void menu_menu();
        void print_print();
        void sound_soundopts();
        void textedit_tesave();
        void time_vbl();
        void vdriver_refresh();
        void wind_wind();
    }
    void ReferenceAllTraps()
    {
        ReferenceTraps::rsys_adb();
        ReferenceTraps::rsys_gestalt();
        ReferenceTraps::rsys_osutil();
        ReferenceTraps::rsys_serial();
        ReferenceTraps::rsys_stdfile();
        ReferenceTraps::base_emustubs();
        ReferenceTraps::ctl_ctl();
        ReferenceTraps::dial_dial();
        ReferenceTraps::ADB();
        ReferenceTraps::AliasMgr();
        ReferenceTraps::AppleEvents();
        ReferenceTraps::BinaryDecimal();
        ReferenceTraps::CodeFragments();
        ReferenceTraps::ControlMgr();
        ReferenceTraps::CQuickDraw();
        ReferenceTraps::DeskMgr();
        ReferenceTraps::DeviceMgr();
        ReferenceTraps::DialogMgr();
        ReferenceTraps::DiskInit();
        ReferenceTraps::Displays();
        ReferenceTraps::EditionMgr();
        ReferenceTraps::FileMgr();
        ReferenceTraps::Finder();
        ReferenceTraps::FontMgr();
        ReferenceTraps::Gestalt();
        ReferenceTraps::HelpMgr();
        ReferenceTraps::Iconutil();
        ReferenceTraps::IntlUtil();
        ReferenceTraps::ListMgr();
        ReferenceTraps::MemoryMgr();
        ReferenceTraps::MenuMgr();
        ReferenceTraps::MixedMode();
        ReferenceTraps::NotifyMgr();
        ReferenceTraps::OSEvent();
        ReferenceTraps::OSUtil();
        ReferenceTraps::Package();
        ReferenceTraps::PrintMgr();
        ReferenceTraps::ProcessMgr();
        ReferenceTraps::QuickDraw();
        ReferenceTraps::QuickTime();
        ReferenceTraps::ResourceMgr();
        ReferenceTraps::SANE();
        ReferenceTraps::ScrapMgr();
        ReferenceTraps::ScriptMgr();
        ReferenceTraps::SegmentLdr();
        ReferenceTraps::Serial();
        ReferenceTraps::ShutDown();
        ReferenceTraps::SoundMgr();
        ReferenceTraps::SpeechManager();
        ReferenceTraps::StdFilePkg();
        ReferenceTraps::SysErr();
        ReferenceTraps::TextEdit();
        ReferenceTraps::TimeMgr();
        ReferenceTraps::ToolboxEvent();
        ReferenceTraps::ToolboxUtil();
        ReferenceTraps::VRetraceMgr();
        ReferenceTraps::WindowMgr();
        ReferenceTraps::list_list();
        ReferenceTraps::menu_menu();
        ReferenceTraps::print_print();
        ReferenceTraps::sound_soundopts();
        ReferenceTraps::textedit_tesave();
        ReferenceTraps::time_vbl();
        ReferenceTraps::vdriver_refresh();
        ReferenceTraps::wind_wind();
    }
}
