namespace Executor {
    namespace ReferenceTraps {
        void ADB();
        void AliasMgr();
        void AppleEvents();
        void BinaryDecimal();
        void ControlMgr();
        void CQuickDraw();
        void DeskMgr();
        void DeviceMgr();
        void DialogMgr();
        void DiskInit();
        void EditionMgr();
        void FileMgr();
        void Finder();
        void FontMgr();
        void Gestalt();
        void HelpMgr();
        void Iconutil();
        void IntlUtil();
        void ListMgr();
        void MemoryMgr();
        void MenuMgr();
        void NotifyMgr();
        void OSEvent();
        void OSUtil();
        void Package();
        void PrintMgr();
        void ProcessMgr();
        void QuickDraw();
        void QuickTime();
        void ResourceMgr();
        void SANE();
        void ScrapMgr();
        void ScriptMgr();
        void SegmentLdr();
        void Serial();
        void ShutDown();
        void SoundMgr();
        void SpeechManager();
        void StdFilePkg();
        void SysErr();
        void TextEdit();
        void TimeMgr();
        void ToolboxEvent();
        void ToolboxUtil();
        void VRetraceMgr();
        void WindowMgr();
        void rsys_adb();
        void rsys_cfm();
        void rsys_ctl();
        void rsys_emustubs();
        void rsys_gestalt();
        void rsys_list();
        void rsys_menu();
        void rsys_mixed_mode();
        void rsys_osutil();
        void rsys_print();
        void rsys_refresh();
        void rsys_serial();
        void rsys_soundopts();
        void rsys_stdfile();
        void rsys_tesave();
        void rsys_vbl();
        void rsys_wind();
    }
    void ReferenceAllTraps()
    {
        ReferenceTraps::ADB();
        ReferenceTraps::AliasMgr();
        ReferenceTraps::AppleEvents();
        ReferenceTraps::BinaryDecimal();
        ReferenceTraps::ControlMgr();
        ReferenceTraps::CQuickDraw();
        ReferenceTraps::DeskMgr();
        ReferenceTraps::DeviceMgr();
        ReferenceTraps::DialogMgr();
        ReferenceTraps::DiskInit();
        ReferenceTraps::EditionMgr();
        ReferenceTraps::FileMgr();
        ReferenceTraps::Finder();
        ReferenceTraps::FontMgr();
        ReferenceTraps::Gestalt();
        ReferenceTraps::HelpMgr();
        ReferenceTraps::Iconutil();
        ReferenceTraps::IntlUtil();
        ReferenceTraps::ListMgr();
        ReferenceTraps::MemoryMgr();
        ReferenceTraps::MenuMgr();
        ReferenceTraps::NotifyMgr();
        ReferenceTraps::OSEvent();
        ReferenceTraps::OSUtil();
        ReferenceTraps::Package();
        ReferenceTraps::PrintMgr();
        ReferenceTraps::ProcessMgr();
        ReferenceTraps::QuickDraw();
        ReferenceTraps::QuickTime();
        ReferenceTraps::ResourceMgr();
        ReferenceTraps::SANE();
        ReferenceTraps::ScrapMgr();
        ReferenceTraps::ScriptMgr();
        ReferenceTraps::SegmentLdr();
        ReferenceTraps::Serial();
        ReferenceTraps::ShutDown();
        ReferenceTraps::SoundMgr();
        ReferenceTraps::SpeechManager();
        ReferenceTraps::StdFilePkg();
        ReferenceTraps::SysErr();
        ReferenceTraps::TextEdit();
        ReferenceTraps::TimeMgr();
        ReferenceTraps::ToolboxEvent();
        ReferenceTraps::ToolboxUtil();
        ReferenceTraps::VRetraceMgr();
        ReferenceTraps::WindowMgr();
        ReferenceTraps::rsys_adb();
        ReferenceTraps::rsys_cfm();
        ReferenceTraps::rsys_ctl();
        ReferenceTraps::rsys_emustubs();
        ReferenceTraps::rsys_gestalt();
        ReferenceTraps::rsys_list();
        ReferenceTraps::rsys_menu();
        ReferenceTraps::rsys_mixed_mode();
        ReferenceTraps::rsys_osutil();
        ReferenceTraps::rsys_print();
        ReferenceTraps::rsys_refresh();
        ReferenceTraps::rsys_serial();
        ReferenceTraps::rsys_soundopts();
        ReferenceTraps::rsys_stdfile();
        ReferenceTraps::rsys_tesave();
        ReferenceTraps::rsys_vbl();
        ReferenceTraps::rsys_wind();
    }
}
